version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-app"
s3_bucket = "cloud-resume-app"
region = "af-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"aws\" DDBTableName=\"visitorTable\""
image_repositories = []
