version: '3.7'

services: 
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks: 
      - aws-local-network

networks: 
  aws-local-network:
    driver: bridge